### ISSUE TITLE
[Bug report] build报错 Please check your GenerateSW plugin configuration: The handler name provided is not valid:networkFirst

### ISSUE THREAD

**Issue by shiqwang** [pipipi-pikachu/PPTist#174]
$ yarn build
Debugger attached.
yarn run v1.22.19
$ vue-cli-service build
Debugger attached.
All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.

⠙  Building for production...Debugger attached.
Debugger attached.
⠼  Building for production...Debugger attached.
⠦  Building for production...Debugger attached.
Debugger attached.
⠋  Building for production...Debugger attached.
⠙  Building for production...Debugger attached.
Debugger attached.
⠸  Building for production...Debugger attached.
⠏  Building for production...

 ERROR  Failed to compile with 1 error                                                                                                15:16:48

 error  

Please check your GenerateSW plugin configuration:
The handler name provided is not valid:networkFirst

 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at /Users/x/Work/git/PPTist/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
    at /Users/x/Work/git/PPTist/node_modules/webpack/lib/webpack.js:148:8
    at /Users/x/Work/git/PPTist/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/x/Work/git/PPTist/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/x/Work/git/PPTist/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/Users/x/Work/git/PPTist/node_modules/webpack/lib/Cache.js:150:23)
    at /Users/x/Work/git/PPTist/node_modules/webpack/lib/Compiler.js:1225:15
    at Hook.eval [as callAsync] (eval at create (/Users/x/Work/git/PPTist/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/x/Work/git/PPTist/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/Users/x/Work/git/PPTist/node_modules/webpack/lib/Compiler.js:1218:23)
    at /Users/x/Work/git/PPTist/node_modules/webpack/lib/webpack.js:147:16
    at finalCallback (/Users/x/Work/git/PPTist/node_modules/webpack/lib/Compiler.js:441:32)
    at /Users/x/Work/git/PPTist/node_modules/webpack/lib/Compiler.js:458:13
    at Hook.eval [as callAsync] (eval at create (/Users/x/Work/git/PPTist/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/x/Work/git/PPTist/node_modules/tapable/lib/Hook.js:18:14)
    at onCompiled (/Users/x/Work/git/PPTist/node_modules/webpack/lib/Compiler.js:456:21)
    at /Users/x/Work/git/PPTist/node_modules/webpack/lib/Compiler.js:1196:17
    at eval (eval at create (/Users/x/Work/git/PPTist/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Waiting for the debugger to disconnect...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Waiting for the debugger to disconnect...

**Comment by pipipi-pikachu** [comment]
这和 #173 一样都是依赖的问题，注意依赖版本（你可以尝试保留 package-lock.json 文件并使用npm安装）
